max_width = 80
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
imports_granularity = "Crate" 
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 80